#ifndef KLEE_EXPRSMTLIBPRINTER_H
#define KLEE_EXPRSMTLIBPRINTER_H

#include <ostream>
#include <string>
#include <klee/Constraints.h>

namespace klee {

///Base Class for SMTLIBv2 printer for Expr trees
class ExprSMTLIBPrinter
{
public:
	///Output stream to write to
	std::ostream& o;
	const ConstraintManager& cm;

	ExprSMTLIBPrinter(std::ostream& output, const ConstraintManager& constraintM) : o(output), cm(constraintM) {}

	void generateOutput();

	enum Logics
	{
		QF_ABV,
		QF_AUFBV
	};

protected:

	virtual void printNotice() { o << "; This file conforms to SMTLIBv2 and was generated by KLEE" << std::endl;}

	virtual void printOptions() { };

	virtual void printSetLogic(ExprSMTLIBPrinter::Logics logic);

	virtual void printArrayDeclarations();

	virtual void printConstraints();

	///Print the S-expression(s) to ask for satisfiability, get-value etc...
	virtual void printAction();

};

}

#endif
