language: cpp
compiler:
    - gcc
    - clang
# TODO env:
before_install:
    - sudo echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.4 main" >> /etc/sources.list.d/llvm.list
    - sudo echo "deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.4 main" >> /etc/sources.list.d/llvm.list
    # Needed for new libstdc++ and gcc4.8
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test/
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt update
    - sudo apt install llvm3.4 llvm3.4-dev clang3.4
